/** Constant and non-editable values used across the codebase */
const Constants = Object.freeze({
    MSG_TYPES: {
        CREATE_ACCOUNT: "create_account",
        LOGIN: "login",
        JOIN_GAME: "join_game",
        CONNECTION_REFUSED: "connection_refused",
        DISCONNECT: "disconnect",
        PING: "ping",
        PLAYER_INSTANTIATED: "instantiated",
        GAME_UPDATE: "update",
        INPUT: "input",
        CLICK: "click",
        INTERACT: "interact",
        DROP: "drop",
        SWAP: "swap",
        DEAD: "dead",
        SEND_MESSAGE: "send",
        RECEIVE_MESSAGE: "receive",
        KICK: "kick",
        BAN: "ban",
    },
    ASSETS: {
        MISSING_TEXTURE: "MissingTexture.png",
        PLAYER: "BlonktoPlayer.png",
        TILE: "Tile.png",
        GRASS_FLOOR: "GrassFloor.png",
        WOOD_FLOOR: "WoodFloor.png",
        WOOD: "Wood.png",
        SPACE_BG: "SpaceBg.png",
        STONE_BLOCK: "StoneBlock.png",
        PIG: "Pig.png",
        SWORD: "Sword.png",
        PICKAXE: "Pickaxe.png",
        AXE: "Axe.png",
        SHOVEL: "Shovel.png",
        RAW_PORK: "RawPork.png",
        TREE_TRUNK: "TreeTrunk.png",
    },
    SHAPES: {
        NONE: 0,
        SQUARE: 1,
        CIRCLE: 2,
    },
    COMMAND_ARGUMENTS: {
        KEY: 0,
        PLAYER: 1,
        STRING: 2,
        INT: 3,
        FLOAT: 4,
        BOOLEAN: 5,
    },
    MINE_TYPES: {
        MINE: 0,
        CHOP: 1,
    },
});

export default Constants;