/** Constant and non-editable values used across the codebase */
const Constants = Object.freeze({
    MSG_TYPES: {
        JOIN_GAME: "join_game",
        CONNECTION_REFUSED: "connection_refused",
        DISCONNECT: "disconnect",
        PING: "ping",
        PLAYER_INSTANTIATED: "instantiated",
        GAME_UPDATE: "update",
        INPUT: "input",
        CLICK: "click",
        INTERACT: "interact",
        DROP: "drop",
        SWAP: "swap",
        CRAFT: "craft",
        DEAD: "dead",
        SEND_MESSAGE: "send",
        RECEIVE_MESSAGE: "receive",
        KICK: "kick",
        BAN: "ban",
    },
    ONE_TIME_MSG_TYPES: {
        PUSH: "push",
        SET_POS: "set_pos",
        SET_COLOR: "set_color",
        SET_GAMEMODE: "set_gamemode",
        RECIPES: "recipes",
        DARKNESS: "derkness",
    },
    ASSETS: {
        MISSING_TEXTURE: "MissingTexture",
        PLAYER: "BlonktoPlayer",
        TILE: "Tile",
        WOOD_WALL: "WoodWall",
        STONE_WALL: "StoneWall",
        GRASS_FLOOR: "GrassFloor",
        WOOD_FLOOR: "WoodFloor",
        STONE_FLOOR: "StoneFloor",
        WOOD: "Wood",
        STONE: "Stone",
        SPACE_BG: "SpaceBg",
        STONE_BLOCK: "StoneBlock",
        PIG: "Pig",
        SWORD: "Sword",
        PICKAXE: "Pickaxe",
        AXE: "Axe",
        SHOVEL: "Shovel",
        RAW_PORK: "RawPork",
        TREE_TRUNK: "TreeTrunk",
        ZOMBIE: "Zombie",
        WOOD_DOOR: "WoodDoor",
        WOOD_DOOR_OPEN: "WoodDoor_Open",
        PINE_CONE: "PineCone",
        SAPLING: "Sapling",
        CARROT: "Carrot",
        PLANTED_CARROTS: "PlantedCarrots",
        GROWN_CARROTS: "GrownCarrots",
        WORK_BENCH: "WorkBench",
        TORCH: "Torch",
        CHEST: "Chest",
        WOOD_STAIRS_DOWN: "WoodStairs_Down",
        WOOD_STAIRS_UP: "WoodStairs_Up",
        COPPER_ORE_BLOCK: "CopperOreBlock",
        COPPER_ORE: "CopperOre",
        COPPER_BAR: "CopperBar",
    },
    SHAPES: {
        NONE: 0,
        SQUARE: 1,
        CIRCLE: 2,
    },
    COMMAND_ARGUMENTS: {
        KEY: 0,
        STRING: 1,
        STRING_LONG: 2,
        INT: 3,
        FLOAT: 4,
        BOOLEAN: 5,
        USERNAME: 6,
        PLAYER: 7,
    },
    MINE_TYPES: {
        NONE: 0,
        ANY: 1,
        MINE: 2,
        CHOP: 3,
    },
    GAME_MODES: {
        SURVIVAL: "survival",
        CREATIVE: "creative",
        SPECTATOR: "spectator",
    },
    LOG_PRIORITIES: {
        INFO: 10,
        DEBUG: 20,
        WARNING: 30,
        ERROR: 40,
    },
    LOG_CATEGORIES: {
        NONE: "none",
        SERVER: "server",
        FILE_MANAGER: "file manager",
        GAME: "game",
        WORLD: "world",
        PERFORMANCE: "performance",
        CHAT: "chat",
        COMPONENT_HANDLER: "component handler",
        REGISTRY: "registry",
        ENTITY: "entity",
        PLAYER_MANAGER: "player manager",
        SOCKET_MANAGER: "socket manager",
    },
    CONSOLE_FORMAT: {
        RESET: "\x1b[0m",
        BOLD: "\x1b[1m",
        ITALIC: "\x1b[3m",
        UNDERLINE: "\x1b[4m",
        FONT_DEFAULT: "\x1b[10m",
        FONT2: "\x1b[11m",
        FONT3: "\x1b[12m",
        FONT4: "\x1b[13m",
        FONT5: "\x1b[14m",
        FONT6: "\x1b[15m",
        IMAGE_NEGATIVE: "\x1b[7m",
        IMAGE_POSITIVE: "\x1b[27m",
        BLACK: "\x1b[30m",
        RED: "\x1b[31m",
        GREEN: "\x1b[32m",
        YELLOW: "\x1b[33m",
        BLUE: "\x1b[34m",
        MAGENTA: "\x1b[35m",
        CYAN: "\x1b[36m",
        WHITE: "\x1b[37m",
        GREY: "\x1b[90m",
        BRIGHT_RED: "\x1b[91m",
        BRIGHT_GREEN: "\x1b[92m",
        BRIGHT_YELLOW: "\x1b[93m",
        BRIGHT_BLUE: "\x1b[94m",
        BRIGHT_MAGENTA: "\x1b[95m",
        BRIGHT_CYAN: "\x1b[96m",
        BRIGHT_WHITE: "\x1b[97m",
        BG_BLACK: "\x1b[40m",
        BG_RED: "\x1b[41m",
        BG_GREEN: "\x1b[42m",
        BG_YELLOW: "\x1b[43m",
        BG_BLUE: "\x1b[44m",
        BG_MAGENTA: "\x1b[45m",
        BG_CYAN: "\x1b[46m",
        BG_WHITE: "\x1b[47m",
        BG_GREY: "\x1b[100m",
        BG_BRIGHT_RED: "\x1b[101m",
        BG_BRIGHT_GREEDN: "\x1b[102m",
        BG_BRIGHT_YELLOW: "\x1b[103m",
        BG_BRIGHT_BLUE: "\x1b[104m",
        BG_BRIGHT_MAGENTA: "\x1b[105m",
        BG_BRIGHT_CYAN: "\x1b[106m",
        BG_BRIGHT_WHITE: "\x1b[107m",
    },
});

export default Constants;
