import Registry from "./registry.js";
import CommandDefinition from "../definitions/commandDefinition.js";
import Logger from "../../server/logging/logger.js";

import Constants from "../../shared/constants.js";
const { LOG_CATEGORIES } = Constants;

const logger = Logger.getLogger(LOG_CATEGORIES.REGISTRY);
logger.info("Initializing command registry");

const CommandRegistry = new Registry<CommandDefinition>("CommandRegistry");

export default CommandRegistry;

import opCommand from "../commands/opCommand.js";
opCommand();
import deopCommand from "../commands/deopCommand.js";
deopCommand();
import oppedCommand from "../commands/oppedCommand.js";
oppedCommand();
import opListCommand from "../commands/opListCommand.js";
opListCommand();
import tpCommand from "../commands/tpCommand.js";
tpCommand();
import pingCommand from "../commands/pingCommand.js";
pingCommand();
import nickCommand from "../commands/nickCommand.js";
nickCommand();
import helpCommand from "../commands/helpCommand.js";
helpCommand();
import killCommand from "../commands/killCommand.js";
killCommand();
import saveWorldCommand from "../commands/saveWorldCommand.js";
saveWorldCommand();
import kickCommand from "../commands/kickCommand.js";
kickCommand();
import banCommand from "../commands/banCommand.js";
banCommand();
import pardonCommand from "../commands/pardonCommand.js";
pardonCommand();
import isBannedCommand from "../commands/isBannedCommand.js";
isBannedCommand();
import banListCommand from "../commands/banListCommand.js";
banListCommand();
import clearBanListCommand from "../commands/clearBanListCommand.js";
clearBanListCommand();
import clearOpListCommand from "../commands/clearOpListCommand.js";
clearOpListCommand();
import giveCommand from "../commands/giveCommand.js";
giveCommand();
import broadcastCommand from "../commands/broadcastCommand.js";
broadcastCommand();
import spawnCommand from "../commands/spawnCommand.js";
spawnCommand();
import clearCommand from "../commands/clearCommand.js";
clearCommand();
import performanceCommand from "../commands/performanceCommand.js";
performanceCommand();
import damageCommand from "../commands/damageCommand.js";
damageCommand();
import setBlockCommand from "../commands/setBlockCommand.js";
setBlockCommand();
import setFloorCommand from "../commands/setFloorCommand.js";
setFloorCommand();
import setBaseFloorCommand from "../commands/setBaseFloorCommand.js";
setBaseFloorCommand();
import setTimeCommand from "../commands/setTimeCommand.js";
setTimeCommand();
import recentLogonsCommand from "../commands/recentLogonsCommand.js";
recentLogonsCommand();
import whitelistCommand from "../commands/whitelistCommand.js";
whitelistCommand();
import setColorCommand from "../commands/setColorCommand.js";
setColorCommand();
import posCommand from "../commands/posCommand.js";
posCommand();
import entityCountCommand from "../commands/entityCountCommand.js";
entityCountCommand();
import healCommand from "../commands/healCommand.js";
healCommand();
import godModeCommand from "../commands/godModeCommand.js";
godModeCommand();
import cycleDayCommand from "../commands/cycleDayCommand.js";
cycleDayCommand();
import getTimeCommand from "../commands/getTimeCommand.js";
getTimeCommand();
import seedCommand from "../commands/seedCommand.js";
seedCommand();
